services:
  db:
    container_name: logvera-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: logvera
      POSTGRES_PASSWORD: logvera
      POSTGRES_DB: logvera
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
